url: "https://ykaisen.github.io/"
# Basic Information 
title: Kaisen Yang
subtitle: 0009-0000-6376-601X
position: Graduate Research Asistant
# subposition: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# subposition_link: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
affiliation: Virginia Tech
subaffiliation: Center for Power Electronics Systems
affiliation_link: https://vt.edu/
subaffiliation_link: https://cpes.vt.edu/
email: kaisenyang@vt.edu
address: 1185 Perry St. Blacksburg, VA 24061
address_link: https://maps.app.goo.gl/3BR54dfmTgvwJrqa8



# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: minimal light
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light-theme.yliu.me/

# Links 
# If you don't need one of them, you may delete the corresponding line.
# google_scholar: https://scholar.google.com/citations?user=bePCCD8AAAAJ&hl=en
cv_link: ./assets/files/CV_Kaisen_MSc.pdf
github_link: https://github.com/YKaisen
linkedin: https://www.linkedin.com/in/kaisenyang/
orcid: https://orcid.org/0009-0000-6376-601X
instagram: https://www.instagram.com/yks0576?igsh=MzNlNGNkZWQ4Mg==

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: assets/img/DSC06981-2.jpg
# logo: ./assets/img/logo.png
favicon: ./assets/img/getimage.jpg
favicon_dark: ./assets/img/getimage.jpg

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
